import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams, Link } from 'react-router-dom';
import api from './services/api';
import { useAuth } from './AuthContext';
import { DataTable, EmptyState, ErrorState, LoadingState, Modal, PageIntro, StatCard, StatusBadge, Unavailable } from './components';

function useAsync(load, deps = []) { const [state, setState] = useState({ loading: true, error: '', data: null }); const reload = async () => { setState({ loading: true, error: '', data: null }); try { const result = await load(); setState({ loading: false, error: '', data: result?.data ?? result }); } catch (error) { setState({ loading: false, error: error.message, data: null }); } }; useEffect(() => { reload(); }, deps); return { ...state, reload }; }
function formatDate(date) { return date ? new Date(date).toLocaleDateString(undefined, { day: '2-digit', month: 'short', year: 'numeric' }) : '--'; }

export function CommandCenter() {
  const health = useAsync(api.health, []);
  const timetable = useAsync(() => api.timetables('?isActive=true'), []);
  const active = useAsync(api.activeSession, []);
  const students = useAsync(() => api.students('?isActive=true'), []);
  const teachers = useAsync(api.teachers, []);
  const subjects = useAsync(() => api.subjects('?isActive=true'), []);
  const countValue = (resource) => resource.loading ? '...' : resource.error ? '--' : resource.data?.length ?? 0;
  const countDetail = (resource, noun) => resource.loading ? 'Loading from backend' : resource.error ? 'Could not load from backend' : `${noun} from backend`;
  return <>
    <PageIntro eyebrow="TODAY / OPERATIONS" title="The room at a glance"><span>One calm view of the attendance system. Live state comes from the backend; no frontend calculations alter attendance.</span></PageIntro>
    <div className="stat-grid">
      <StatCard label="Active students" value={countValue(students)} detail={countDetail(students, 'Registered active students')} />
      <StatCard label="Teachers" value={countValue(teachers)} detail={countDetail(teachers, 'Registered teachers')} tone="warm" />
      <StatCard label="Active subjects" value={countValue(subjects)} detail={countDetail(subjects, 'Available subjects')} />
      <StatCard label="Active session" value={active.loading ? '...' : active.error ? 'ERROR' : active.data ? 'LIVE' : 'NONE'} detail={active.error || active.data?.subjectId?.name || 'No session currently open'} tone="green" />
    </div>
    <div className="dashboard-grid">
      <section className="panel panel-large">
        <div className="panel-head">
          <div><p className="eyebrow">SCHEDULE</p><h3>Active timetable</h3></div>
          <Link className="text-link" to="/admin/timetable">Manage timetable →</Link>
        </div>
        {timetable.loading
          ? <LoadingState label="Loading timetable" />
          : timetable.error
            ? <ErrorState error={timetable.error} onRetry={timetable.reload} />
            : <DataTable
              columns={[
                { key: 'dayOfWeek', label: 'Day' },
                { key: 'startTime', label: 'Time' },
                { key: 'subjectId', label: 'Subject', render: (row) => row.subjectId?.name || row.subjectId?.code || '--' },
                { key: 'classId', label: 'Class', render: (row) => row.classId ? `${row.classId.name} / ${row.classId.section}` : '--' },
                { key: 'room', label: 'Room' }
              ]}
              rows={timetable.data || []}
              empty="No active timetable entries"
            />}
      </section>
      <section className="panel signal-panel">
        <p className="eyebrow">SYSTEM SIGNAL</p>
        <h3>Backend health</h3>
        <div className={`signal ${health.data?.database === 'connected' ? 'good' : 'muted'}`}>
          <span className="status-dot" />
          {health.loading ? 'Checking connection' : health.error ? 'Health check failed' : health.data?.database === 'connected' ? 'MongoDB connected' : 'Database unavailable'}
        </div>
        {health.error && <p className="muted" role="alert">{health.error}</p>}
        <p className="muted">The dashboard uses the API configured in <code>VITE_API_BASE_URL</code>.</p>
        <Link className="button primary" to="/teacher/start-attendance">Start a session</Link>
      </section>
    </div>
  </>;
}

const unavailablePages = { '/admin/students': ['STUDENT DIRECTORY', 'Students'], '/admin/teachers': ['STAFF DIRECTORY', 'Teachers'], '/admin/subjects': ['ACADEMIC CATALOG', 'Subjects'], '/admin/classes': ['COHORTS', 'Classes'], '/admin/reports': ['ADMINISTRATION', 'Reports'] };
export function UnavailablePage({ kind }) { const [eyebrow, title] = unavailablePages[kind] || ['WORKSPACE', 'Coming soon']; return <><PageIntro eyebrow={eyebrow} title={title}>The page is intentionally connected to the current backend contract.</PageIntro><Unavailable title={`${title} API not available`} /></>; }

function TimetableForm({ initial, onClose, onSaved }) { const [form, setForm] = useState(initial || { classId: '', subjectId: '', teacherId: '', dayOfWeek: 'MONDAY', startTime: '09:00', endTime: '10:00', room: '' }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const save = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { if (initial?._id) await api.updateTimetable(initial._id, form); else await api.createTimetable(form); onSaved(); onClose(); } catch (e) { setError(e.message); } finally { setSaving(false); } }; return <Modal title={initial ? 'Edit timetable entry' : 'Add timetable entry'} onClose={onClose}><form className="form-grid" onSubmit={save}>{[['classId','Class ID'],['subjectId','Subject ID'],['teacherId','Teacher ID'],['room','Room']].map(([key,label]) => <label key={key}>{label}<input required={key !== 'room'} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} placeholder={key === 'room' ? 'Lab 02' : 'MongoDB ObjectId'} /></label>)}<label>Day<select value={form.dayOfWeek} onChange={(e) => setForm({ ...form, dayOfWeek: e.target.value })}>{['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY'].map((day) => <option key={day}>{day}</option>)}</select></label><label>Start time<input type="time" value={form.startTime} onChange={(e) => setForm({ ...form, startTime: e.target.value })} /></label><label>End time<input type="time" value={form.endTime} onChange={(e) => setForm({ ...form, endTime: e.target.value })} /></label>{error && <div className="form-error">{error}</div>}<div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={saving}>{saving ? 'Saving...' : 'Save entry'}</button></div></form></Modal>; }
export function TimetablePage() { const [filter, setFilter] = useState(''); const [editing, setEditing] = useState(null); const data = useAsync(() => api.timetables(filter ? `?dayOfWeek=${filter}` : ''), [filter]); const deactivate = async (id) => { if (!window.confirm('Deactivate this timetable entry?')) return; try { await api.deactivateTimetable(id); data.reload(); } catch (e) { window.alert(e.message); } }; return <><PageIntro eyebrow="ADMIN / SCHEDULE" title="Timetable" action={<button className="button primary" onClick={() => setEditing({})}>+ Add entry</button>}>The timetable is the source of truth for subject, class, teacher, and session context.</PageIntro><div className="toolbar"><select value={filter} onChange={(e) => setFilter(e.target.value)}><option value="">All days</option>{['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY'].map((day) => <option key={day}>{day}</option>)}</select><span className="toolbar-note">Backend validates references and slot conflicts.</span></div>{data.loading ? <LoadingState label="Loading timetable" /> : data.error ? <ErrorState error={data.error} onRetry={data.reload} /> : <DataTable columns={[{ key:'dayOfWeek', label:'Day' }, { key:'startTime', label:'Start' }, { key:'endTime', label:'End' }, { key:'subjectId', label:'Subject', render:r=>r.subjectId?.name || r.subjectId?.code || '--' }, { key:'classId', label:'Class', render:r=>r.classId ? `${r.classId.name} / ${r.classId.section}` : '--' }, { key:'teacherId', label:'Teacher', render:r=>r.teacherId?.name || '--' }, { key:'room', label:'Room' }, { key:'isActive', label:'Status', render:r=><StatusBadge value={r.isActive ? 'ACTIVE' : 'INACTIVE'} /> }, { key:'actions', label:'', render:r=><div className="row-actions"><button className="table-action" onClick={()=>setEditing(r)}>Edit</button><button className="table-action danger" onClick={()=>deactivate(r._id)}>Deactivate</button></div> }]} rows={data.data || []} empty="No timetable entries" />}{editing && <TimetableForm initial={editing._id ? editing : null} onClose={()=>setEditing(null)} onSaved={data.reload} />}</>; }

export function StartAttendance() { const data = useAsync(() => api.timetables('?isActive=true'), []); const [notice, setNotice] = useState(''); const navigate = useNavigate(); const { user } = useAuth(); const start = async (id) => { setNotice(''); try { const result = await api.startSession(id); const route = user?.role === 'ADMIN' ? '/admin/live-attendance' : '/teacher/live-attendance'; navigate(`${route}?session=${result.data._id}`); } catch (e) { setNotice(e.message); } }; return <><PageIntro eyebrow="ATTENDANCE / SESSION CONTROL" title="Start attendance">Select an active timetable slot. The backend checks your assignment and eligibility before creating a session.</PageIntro>{notice && <div className="notice error-state" role="alert">{notice}</div>}{data.loading ? <LoadingState label="Loading eligible timetable" /> : data.error ? <ErrorState error={data.error} onRetry={data.reload} /> : <div className="schedule-grid">{(data.data || []).map((item) => <article className="schedule-card" key={item._id}><div className="schedule-time"><span>{item.dayOfWeek}</span><strong>{item.startTime}</strong><small>to {item.endTime}</small></div><div className="schedule-details"><h3>{item.subjectId?.name || item.subjectId?.code || 'Subject unavailable'}</h3><p>{item.classId?.name} / {item.classId?.section}</p><small>{item.teacherId?.name || 'Teacher'} · {item.room || 'Room not set'}</small></div><button className="button primary" onClick={()=>start(item._id)}>Start session</button></article>)}{!data.data?.length && <EmptyState title="No eligible timetable entries">Create an active timetable entry before starting attendance.</EmptyState>}</div>}</>; }

export function LiveAttendance() { const query = new URLSearchParams(window.location.search); const [sessionId, setSessionId] = useState(query.get('session') || ''); const active = useAsync(() => api.activeSession(), []); const [live, setLive] = useState({ loading: true, error: '', data: null }); const [closed, setClosed] = useState(false); const loadLive = async (id) => { if (!id) return; try { const result = await api.liveAttendance(id); setLive({ loading:false, error:'', data:result.data }); } catch(e) { setLive({ loading:false, error:e.message, data:null }); } }; useEffect(() => { const id = sessionId || active.data?._id; if (id) { setSessionId(id); loadLive(id); } }, [active.data?._id, sessionId]); useEffect(() => { if (!sessionId || closed) return undefined; const interval = window.setInterval(() => loadLive(sessionId), 4000); return () => window.clearInterval(interval); }, [sessionId, closed]); const close = async () => { try { await api.closeSession(sessionId); setClosed(true); await loadLive(sessionId); } catch(e) { setLive({ ...live, error:e.message }); } }; if (active.loading && !sessionId) return <LoadingState label="Finding active session" />; if (!sessionId && !active.data) return <><PageIntro eyebrow="TEACHING / LIVE" title="Live attendance" /><EmptyState title="No active session">Start an attendance session first.</EmptyState></>; const data = live.data; return <><PageIntro eyebrow="TEACHING / LIVE ATTENDANCE" title="Live attendance" action={!closed && <button className="button danger-button" onClick={close}>Close attendance</button>}><span>{data?.session?.subjectId?.name || data?.session?.subjectId?.code || 'Subject'} · {data?.session?.classId?.name || '--'} / {data?.session?.classId?.section || '--'} · {data?.session?.startTime || '--'}–{data?.session?.endTime || '--'}</span></PageIntro>{live.error ? <ErrorState error={live.error} onRetry={()=>loadLive(sessionId)} /> : live.loading ? <LoadingState label="Loading live attendance" /> : <><div className="stat-grid live-stats"><StatCard label="Total students" value={data.counts.totalStudents} /><StatCard label="In class" value={data.counts.inClass} tone="green" /><StatCard label="Outside" value={data.counts.outside} tone="warm" /><StatCard label="Not scanned" value={data.counts.notScanned} /></div>{closed && <div className="notice success">Session closed. Final statuses are now owned by the backend.</div>}<DataTable columns={[{key:'student',label:'Student',render:r=><b>{r.student.name}</b>},{key:'roll',label:'Roll number',render:r=>r.student.rollNumber},{key:'currentState',label:'Current state',render:r=><StatusBadge value={r.currentState} />},{key:'subjectAttendancePercentage',label:'Subject attendance',render:r=><strong>{r.subjectAttendancePercentage}%</strong>}]} rows={data.students} empty="No students in this class" /></>}</>; }

export function Register() { const data = useAsync(() => api.register(''), []); return <><PageIntro eyebrow="TEACHING / RECORDS" title="Attendance register">Final status is distinct from live movement state. This view reads finalized records from MongoDB.</PageIntro><div className="toolbar"><span className="toolbar-note">Filters can be added as the student/class CRUD APIs become available.</span></div>{data.loading ? <LoadingState label="Loading attendance records" /> : data.error ? <ErrorState error={data.error} onRetry={data.reload} /> : <DataTable columns={[{key:'studentId',label:'Student',render:r=><b>{r.studentId?.name || '--'}</b>},{key:'roll',label:'Roll number',render:r=>r.studentId?.rollNumber || '--'},{key:'subjectId',label:'Subject',render:r=>r.subjectId?.name || r.subjectId?.code || '--'},{key:'date',label:'Date',render:r=>formatDate(r.date)},{key:'finalStatus',label:'Final status',render:r=><StatusBadge value={r.finalStatus} />},{key:'sessionId',label:'Session',render:r=>r.sessionId?.status || '--'}]} rows={data.data || []} empty="No attendance records yet" />}</>; }

export function SubjectReports() { const [studentId, setStudentId] = useState(localStorage.getItem('demoStudentId') || ''); const [submitted, setSubmitted] = useState(''); const data = useAsync(() => submitted ? api.studentAttendance(submitted) : Promise.resolve({ data: [] }), [submitted]); return <><PageIntro eyebrow="TEACHING / ANALYTICS" title="Subject reports">Percentages come directly from the backend and are calculated from closed attendance records.</PageIntro><div className="lookup-bar"><input value={studentId} onChange={(e)=>setStudentId(e.target.value)} placeholder="Enter student ID for demo lookup" /><button className="button primary" onClick={()=>{localStorage.setItem('demoStudentId',studentId);setSubmitted(studentId);}}>Load report</button></div>{data.loading ? <LoadingState label="Loading subject analytics" /> : data.error ? <ErrorState error={data.error} onRetry={data.reload} /> : <div className="report-grid">{(data.data || []).map((item)=><article className="report-card" key={item.subject?._id}><p>{item.subject?.code || item.subject?.name}</p><strong>{item.attendancePercentage}%</strong><span>{item.presentCount} present / {item.completedClassCount} completed</span></article>)}{submitted && !data.data?.length && <EmptyState title="No completed subject records">The student has no closed attendance records.</EmptyState>}</div>}</>; }

export function StudentDashboard({ history = false }) { const [studentId, setStudentId] = useState(localStorage.getItem('demoStudentId') || ''); const [submitted, setSubmitted] = useState(localStorage.getItem('demoStudentId') || ''); const data = useAsync(() => submitted ? api.studentAttendance(submitted) : Promise.resolve({ data: [] }), [submitted]); return <><PageIntro eyebrow={`STUDENT / ${history ? 'HISTORY' : 'ATTENDANCE'}`} title={history ? 'Attendance history' : 'My attendance'}><span>Development lookup only. Production authentication will be implemented in a later phase.</span></PageIntro><div className="lookup-bar"><input value={studentId} onChange={(e)=>setStudentId(e.target.value)} placeholder="Student MongoDB ID" /><button className="button primary" onClick={()=>{localStorage.setItem('demoStudentId',studentId);setSubmitted(studentId);}}>Load my data</button></div>{data.loading ? <LoadingState label="Loading student attendance" /> : data.error ? <ErrorState error={data.error} onRetry={data.reload} /> : history ? <DataTable columns={[{key:'subject',label:'Subject',render:r=>r.subject?.name || r.subject?.code},{key:'presentCount',label:'Present'},{key:'completedClassCount',label:'Completed'},{key:'attendancePercentage',label:'Percentage',render:r=><strong>{r.attendancePercentage}%</strong>}]} rows={data.data || []} empty="No attendance history" /> : <div className="report-grid">{(data.data || []).map((item)=><article className="report-card" key={item.subject?._id}><p>{item.subject?.name || item.subject?.code}</p><strong>{item.attendancePercentage}%</strong><span>{item.presentCount} present / {item.completedClassCount} completed</span></article>)}{submitted && !data.data?.length && <EmptyState title="No attendance yet">Completed subject records will appear here.</EmptyState>}</div>}</>; }
export function StudentProfile() { return <><PageIntro eyebrow="STUDENT / PROFILE" title="Student profile"><span>Use the development lookup on the Attendance page to load real student analytics.</span></PageIntro><EmptyState title="Profile API not available">Student profile CRUD is not exposed by the current backend. No identity data is fabricated here.</EmptyState></>; }
export function Login() { const navigate = useNavigate(); const [role, setRole] = useState('admin'); return <div className="login-page"><div className="login-art"><span className="brand-mark">CP</span><p className="eyebrow">SMART CLASSROOM / DEMO ACCESS</p><h2>A clearer pulse<br />for every room.</h2><p>Observe timetable context, live movement, and subject attendance from one practical workspace.</p></div><form className="login-card" onSubmit={(e)=>{e.preventDefault();navigate(role === 'admin' ? '/' : role === 'teacher' ? '/teacher/start-attendance' : '/student/attendance');}}><p className="eyebrow">WELCOME BACK</p><h1>Open the dashboard</h1><p className="muted">Authentication will be implemented in a later phase. Choose a demo role to explore the connected UI.</p><label>Demo role<select value={role} onChange={(e)=>setRole(e.target.value)}><option value="admin">Admin</option><option value="teacher">Teacher</option><option value="student">Student</option></select></label><button className="button primary wide">Continue as {role}</button></form></div>; }
